name = "birch-swinnerton-dyer-143a1"
version = "0.1.0"
defaultTargets = ["lean", "HassePrimeSet", "BostBound143"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "v4.12.0"

[[lean_lib]]
name = "lean"
srcDir = "lean"

[[lean_lib]]
name = "HassePrimeSet"

[[lean_lib]]
name = "BostBound143"
