/- Towers.lean — Root aggregation for the Towers/BSD tier -/

import Towers.BSD.B01_EllipticCurve
import Towers.BSD.B02_Modularity
import Towers.BSD.B02_Modularity_Closed
import Towers.BSD.B03_LFunction
import Towers.BSD.B06_BSDCollection
import Towers.BSD.BQF_Standalone
import Towers.BSD.BSD_AP_Table
import Towers.BSD.BSD_AP_Table_Closed
import Towers.BSD.BSD_AlgNorm
import Towers.BSD.BSD_AnalyticCapstone
import Towers.BSD.BSD_AnalyticOn_L143a1
import Towers.BSD.BSD_AnalyticRank
import Towers.BSD.BSD_ArakelovHeight_Closed
import Towers.BSD.BSD_BQF_Bridge_Closed
import Towers.BSD.BSD_C22b_LowerBound
import Towers.BSD.BSD_Certificate
import Towers.BSD.BSD_ClassGroupBridge
import Towers.BSD.BSD_ClassGroup_Generator_CLOSED
import Towers.BSD.BSD_ClassNum_Unconditional_CLOSED
import Towers.BSD.BSD_ClassNum_Upper_CLOSED
import Towers.BSD.BSD_ClassNumber
import Towers.BSD.BSD_ClassNumber143
import Towers.BSD.BSD_ClassNumberBounds
import Towers.BSD.BSD_ClassNumberLowerProof
import Towers.BSD.BSD_ClassNumber_Completion_CLOSED
import Towers.BSD.BSD_ClassNumber_UpperBound_CLOSED
import Towers.BSD.BSD_ClayPath
import Towers.BSD.BSD_ClaySubmission
import Towers.BSD.BSD_Clay_6gate_CLOSED
import Towers.BSD.BSD_Clay_Certificate
import Towers.BSD.BSD_Discriminant
import Towers.BSD.BSD_EulerProduct_Closed
import Towers.BSD.BSD_FormIdeal
import Towers.BSD.BSD_FormIdeal_CLOSED
import Towers.BSD.BSD_FourGateCombinator
import Towers.BSD.BSD_FrobeniusAnalytic_Combinator
import Towers.BSD.BSD_Frobenius_Certificate
import Towers.BSD.BSD_Frobenius_Isogeny_Degree_Hasse_143a1_CLOSED
import Towers.BSD.BSD_FuncEq
import Towers.BSD.BSD_GrossZagier_Closed
import Towers.BSD.BSD_GrossZagier_LMFDB
import Towers.BSD.BSD_GrossZagier_v2
import Towers.BSD.BSD_HasseEndDeg_CLOSED
import Towers.BSD.BSD_HasseWeil_Chain
import Towers.BSD.BSD_Hasse_Points_101_113
import Towers.BSD.BSD_Hasse_Points_127_149
import Towers.BSD.BSD_Hasse_Points_151_191
import Towers.BSD.BSD_Hasse_Points_17_29
import Towers.BSD.BSD_Hasse_Points_193_223
import Towers.BSD.BSD_Hasse_Points_227_241
import Towers.BSD.BSD_Hasse_Points_31_67
import Towers.BSD.BSD_Hasse_Points_71_79
import Towers.BSD.BSD_Hasse_Points_83_97
import Towers.BSD.BSD_HeegnerPoint_CLOSED
import Towers.BSD.BSD_IntBasis
import Towers.BSD.BSD_KodairaReduction_CLOSED
import Towers.BSD.BSD_KolyvaginPath
import Towers.BSD.BSD_Kolyvagin_Capstone_Closed
import Towers.BSD.BSD_L143a1_BSDLFunction_ID_PROVED
import Towers.BSD.BSD_L143a1_zero_at_one
import Towers.BSD.BSD_LAnalytic_Anchor_CLOSED
import Towers.BSD.BSD_LFunction
import Towers.BSD.BSD_LFunction_Closed
import Towers.BSD.BSD_MasterCertification
import Towers.BSD.BSD_MasterProof
import Towers.BSD.BSD_Multiplicativity_Closed
import Towers.BSD.BSD_NonTorsion_P20_Closed
import Towers.BSD.BSD_NormBridge
import Towers.BSD.BSD_NormFormBounds
import Towers.BSD.BSD_NumberField
import Towers.BSD.BSD_OrderOf_CLOSED
import Towers.BSD.BSD_P2_Principal_CLOSED
import Towers.BSD.BSD_Ramanujan_from_Discriminant
import Towers.BSD.BSD_RankCapstone
import Towers.BSD.BSD_Rank_Closed
import Towers.BSD.BSD_ReducedForms
import Towers.BSD.BSD_SHA_Tamagawa_Closed
import Towers.BSD.BSD_SemistableReduction_CLOSED
import Towers.BSD.BSD_SubGateChain
import Towers.BSD.BSD_SurfaceClose_CLOSED
import Towers.BSD.BSD_Tamagawa_Scaffold
import Towers.BSD.BSD_Tier3B
import Towers.BSD.BSD_TierC_Certificate
import Towers.BSD.BSD_TorsionBound_CLOSED
import Towers.BSD.BSD_TorsionBound_P2P5_Closed
import Towers.BSD.BSD_TranscendentalSieve
import Towers.BSD.BSD_TwoGateCombinator
import Towers.BSD.BSD_VanishingOrder_143_Genuine
import Towers.BSD.BSD_VanishingOrder_Kolyvagin_Closed
import Towers.BSD.BostBound_143
import Towers.BSD.C02_Modularity_X0_143_Standalone_OPEN
import Towers.BSD.E143a1_CLOSED
import Towers.BSD.Genus_X0_143
import Towers.BSD.HassePrimeSet
import Towers.BSD.Traces_E1859_All_168
