/- Ported closed theorems from birch-swinnerton-dyer-143/BSD_ClassNumberBounds.lean — extracted 14 closed declarations. -/

theorem BSD_ClassNumber_ArithBase :
    (∀ a b : ℤ, a ^ 2 + a * b + 36 * b ^ 2 ≠ 2)   ∧
    (∀ a b : ℤ, a ^ 2 + a * b + 36 * b ^ 2 ≠ 8)   ∧
    (∀ a b : ℤ, a ^ 2 + a * b + 36 * b ^ 2 ≠ 32)  ∧
    (∀ a b : ℤ, a ^ 2 + a * b + 36 * b ^ 2 ≠ 128) ∧
    (∀ a b : ℤ, a ^ 2 + a * b + 36 * b ^ 2 ≠ 512) ∧
    (∀ a b : ℤ, a ^ 2 + a * b + 36 * b ^ 2 ≠ 3)   ∧
    (∀ a b : ℤ, a ^ 2 + a * b + 36 * b ^ 2 ≠ 5)   ∧
    (∀ a b : ℤ, a ^ 2 + a * b + 36 * b ^ 2 ≠ 7)   ∧
    ((-28 : ℤ) ^ 2 + (-28) * 3 + 36 * 3 ^ 2 = 1024) :=
  ⟨norm_form_no_norm_two_BSD, norm_form_no_norm_eight_BSD,
   norm_form_no_norm_32_BSD, norm_form_no_norm_128_BSD,
   norm_form_no_norm_512_BSD, norm_form_no_norm_three_BSD,
   norm_form_no_norm_five_BSD, norm_form_no_norm_seven_BSD,
   norm_form_gen_1024_BSD⟩

-- ============================================================
-- §2. Surface #1 — CLOSED (classical trio, 0 sorry)
-- ============================================================

/-- **CLOSED** (classical trio, 0 sorry):
    Every element of ClassGroup(𝓞 K) has order ≤ classNumber K.

    Proof path:
    1. `NumberField.classNumber K = Fintype.card (ClassGroup (𝓞 K))` by definition.
    2. `instFintypeClassGroup : Fintype (ClassGroup (𝓞 K))` is in Mathlib v4.12.0
       (NumberField/ClassNumber.lean:29).
    3. `orderOf_le_card_univ [Fintype G] : orderOf x ≤ Fintype.card G`.

    This closes surface #1.  `BSD_lower_bound_cert` now uses this directly. -/

theorem BSD_orderOf_le_classNumber_CLOSED :
    ∀ g : ClassGroup (𝓞 K), orderOf g ≤ NumberField.classNumber K := fun g => by
  show orderOf g ≤ Fintype.card (ClassGroup (𝓞 K))
  exact orderOf_le_card_univ

-- ============================================================
-- §3. Surfaces #2 and #3 — OPEN (precise API-gap stubs)
-- ============================================================

/-- **OPEN**: ClassGroup(𝓞 K) has an element of order ≥ 10 (lower bound witness).

    Arithmetic proved (BSD_ClassNumberLowerProof.lean) ✓:
    • absNorm p2_OK = 2                           `absNorm_p2_eq_2` ✓
    • p2_OK^k non-principal for k=1..9 (odd)      `p2_pow_not_principal_odd` ✓
    • (p2_OK^k).IsPrincipal → a²+ab+36b²=2^k     `p2_principal_implies_norm_form` ✓

    Remaining gaps:
    A. Even-k non-principality (k ∈ {2,4,6,8}):
       `EvenK_NonPrincipal_Bridge_p2_OK` — non-ramification + factorization API
       absent in Mathlib v4.12.0.
    B. ClassGroup orderOf bridge:
       Convert `p2_OK^k non-principal` → `orderOf [p2_OK] ≥ 10` in ClassGroup API.
    STATUS: OPEN (weakened to ∃ p2, 10 ≤ orderOf p2).  def Prop. -/
def BSD_orderOf_p2_OPEN : Prop :=
  ∃ (p2 : ClassGroup (𝓞 K)), 10 ≤ orderOf p2

/-- **OPEN**: classNumber K ≤ 10.

    Mathematical route (conditional on #2):
    Minkowski bound (proved) gives: every ideal class has a rep with absNorm < 8,
    so ClassGroup is generated by {[𝔭₂], [𝔭₃], [𝔭₇]}.
    Non-norm proofs show [𝔭₃],[𝔭₇] ∈ ⟨[𝔭₂]⟩ (non-norm for 3,5,7 ✓).
    ⟹ ClassGroup(𝓞 K) = ⟨[𝔭₂]⟩, cyclic of order 10 ⟹ |ClassGroup| = 10.

    Formal gap:
    • ClassGroup generator API: no `ClassGroup.generator_of_minkowski_set` in Mathlib v4.12.0.
    • `Subgroup.orderOf_eq_card` for finitely generated abelian groups not wired for
      AdjoinRoot-based number fields.
    STATUS: OPEN.  def Prop. -/
def BSD_classGroupCard_le_10_OPEN : Prop :=
  NumberField.classNumber K ≤ 10

-- ============================================================
-- §4. Discharge combinators (0 sorry, classical trio)
-- ============================================================

/-- **BSD_lower_bound_cert** (combinator, 0 sorry, classical trio):
    Given `BSD_orderOf_p2_OPEN` (∃ p2 with 10 ≤ orderOf p2), the lower bound
    10 ≤ classNumber K follows via the CLOSED surface #1.

    Proof: obtain p2 with 10 ≤ orderOf p2;
           10 ≤ orderOf p2 ≤ classNumber K  (by BSD_orderOf_le_classNumber_CLOSED).
    Surface #1 (`BSD_orderOf_le_classNumber_CLOSED`) is no longer an open hypothesis. -/

theorem BSD_lower_bound_cert
    (hord : BSD_orderOf_p2_OPEN) :
    10 ≤ NumberField.classNumber K := by
  obtain ⟨p2, hp2⟩ := hord
  calc 10 ≤ orderOf p2                        := hp2
       _  ≤ NumberField.classNumber K          := BSD_orderOf_le_classNumber_CLOSED p2

/-- **BSD_upper_bound_cert** (combinator, 0 sorry, classical trio):
    Given `BSD_classGroupCard_le_10_OPEN` (classNumber K ≤ 10), returns it directly.
    The combinator exists to make the surface dependency explicit in the chain. -/

theorem BSD_upper_bound_cert
    (hcard : BSD_classGroupCard_le_10_OPEN) :
    NumberField.classNumber K ≤ 10 :=
  hcard

/-- **BSD_classNumber_10_cert** (combinator, 0 sorry, classical trio):
    Given the two remaining OPEN surfaces, h(K) = 10.
    Wires into the existing BSD_ClassNumber_discharged chain.
    Surface #1 is discharged; surfaces #2 and #3 remain as explicit hypotheses. -/

theorem BSD_classNumber_10_cert
    (hord  : BSD_orderOf_p2_OPEN)
    (hcard : BSD_classGroupCard_le_10_OPEN) :
    NumberField.classNumber K = 10 :=
  Nat.le_antisymm
    (BSD_upper_bound_cert hcard)
    (BSD_lower_bound_cert hord)

-- ============================================================
-- §5. Proved auxiliary arithmetic
-- ============================================================

/-- PROVED: Minkowski bound (2/π)·√143 < 8. Already in BSD_NumberField.lean. -/

theorem BSD_minkowski_lt_8 : 2 / Real.pi * Real.sqrt 143 < 8 :=
  minkowski_lt_eight_BSD

/-- PROVED: 143 = 11 · 13. -/

theorem BSD_conductor_11_times_13 : (143 : ℕ) = 11 * 13 := by norm_num

-- ============================================================
-- §6. BQF count certificate (proved — 0 sorry, classical trio)
-- ============================================================

/-- **PROVED**: There are exactly 10 reduced BQFs of discriminant -143.
    This is the arithmetic side of the class number computation. -/

theorem BSD_bqf_count_cert : reducedForms143.length = 10 :=
  BSD_numReducedForms143

/-- **PROVED**: All 10 reduced forms are genuine reduced BQFs. -/

theorem BSD_bqf_all_reduced_cert :
    ∀ t ∈ reducedForms143, IsReducedBQF143 t.1 t.2.1 t.2.2 :=
  reducedForms143_all_reduced

/-- **PROVED**: The 10 reduced forms are complete (every reduced BQF of disc -143
    appears in the list). -/

theorem BSD_bqf_completeness_cert (a b c : ℤ) (h : IsReducedBQF143 a b c) :
    (a, b, c) ∈ reducedForms143 :=
  reducedForms143_complete a b c h

-- ============================================================
-- §7. Conditional class number via BQF bridge (combinator)
-- ============================================================

/-- **COMBINATOR** (0 sorry, classical trio):
    Given `BSD_BQF_ClassNumber_bridge_OPEN` (the Gauss–Dirichlet bijection
    reduced-forms ↔ ClassGroup(𝓞 K)), combined with the proved BQF count
    `BSD_numReducedForms143` (length = 10), derive classNumber K = 10.

    Proof: bridge says classNumber K = reducedForms143.length,
    and BSD_numReducedForms143 says reducedForms143.length = 10. -/

theorem BSD_classNumber_via_bqf_bridge
    (h_bridge : BSD_BQF_ClassNumber_bridge_OPEN) :
    NumberField.classNumber K = 10 := by
  unfold BSD_BQF_ClassNumber_bridge_OPEN at h_bridge
  rw [h_bridge]
  exact BSD_numReducedForms143

/-- **COMBINATOR** (0 sorry, classical trio):
    Upper bound: given the BQF bridge, classNumber K ≤ 10. -/

theorem BSD_upper_via_bqf
    (h_bridge : BSD_BQF_ClassNumber_bridge_OPEN) :
    K1_ClassNumber_Upper_BSD :=
  Nat.le_of_eq (BSD_classNumber_via_bqf_bridge h_bridge)

/-- **COMBINATOR** (0 sorry, classical trio):
    Lower bound: given the BQF bridge, 10 ≤ classNumber K. -/

theorem BSD_lower_via_bqf
    (h_bridge : BSD_BQF_ClassNumber_bridge_OPEN) :
    K1_ClassNumber_Lower_BSD :=
  Nat.le_of_eq (BSD_classNumber_via_bqf_bridge h_bridge).symm

-- ============================================================
-- §8. Surface ledger (updated)
-- ============================================================

/-- Surface ledger: surface #1 CLOSED; surfaces #2 and #3 OPEN; BQF count PROVED;
    conditional class number combinator PROVED; zero sorry. -/

theorem BSD_ClassNumberBounds_surface_ledger :
    (∀ g : ClassGroup (𝓞 K), orderOf g ≤ NumberField.classNumber K) ∧  -- #1 CLOSED
    reducedForms143.length = 10 ∧                                        -- BQF count PROVED
    (BSD_classGroupCard_le_10_OPEN → False → False) ∧                   -- #2 OPEN
    (BSD_orderOf_p2_OPEN → False → False) :=                            -- #3 OPEN
  ⟨BSD_orderOf_le_classNumber_CLOSED, BSD_numReducedForms143,
   fun _ h => h, fun _ h => h⟩

end Towers.BSD

